/* =========================================================
   THE POET'S ROOM — POEMS
   ---------------------------------------------------------
   Rich poem lines can contain:
     <br>                 for line breaks within a stanza
     <em>...</em>         for italic emphasis
     <span class="divider"><span>label</span></span>   for a section divider
     <span class="opener">...</span>          for a styled opening line
   ========================================================= */

const poems = [
  {
    id: "her-testament",
    title: "Her Testament",
    date: "2026",
    tags: ["love", "woman", "devotion"],
    cover: "her-testament.PNG",
    lines: [
      "<span class=\"opener\">I want a woman.</span>",
      "Not just any type of woman,<br>but the type that stills my breath<br>when she walks into a room.",
      "The type that makes a grown man<br>forget the sentence he rehearsed<br>because suddenly,<br>there are more important things<br>than finishing a thought.",
      "The type to feed my soul<br>and not just my belly.",
      "A woman with enough depth<br>to drown a shallow man<br>and baptize the one<br>who came prepared to be changed.",
      "The type whose knees<br>have known the ground,<br>whose mouth has carried prayers<br>even the fathers of old<br>were afraid to pray.",
      "Not because she is perfect,<br>but because she knows<br>where perfection ends<br>and grace begins.",
      "I want a woman<br>who is intellectually expensive,<br>the kind of woman<br>I cannot love lazily.",
      "Softly bold.",
      "Emotionally confident.",
      "A woman who can sit across from me<br>and make silence feel like conversation.",
      "And culinarily blessed,<br>because Lord knows<br>a man can read Shakespeare<br>and still be defeated<br>by a well-seasoned plate.",
      "I want the type of woman<br>who carries champagne in her walk,<br>not because she is trying to be noticed,<br>but because elegance<br>has become her natural language.",
      "Her movements immaculate<br>like the sea when it remembers<br>there is no need to hurry.",
      "And when she smiles…<br>I want to smile too.",
      "Not that little polite smile<br>we give people<br>when we are trying to prove<br>we have manners.",
      "I mean the kind of smile<br>that betrays me.",
      "The kind that tells everybody<br>before I say a word:",
      "Yes.<br>I am happy.",
      "The type of woman<br>that would make me walk into church<br>and tell the pastor,",
      "\"Sir, skip the vows.<br>She already knows<br>what I am about to promise.\"",
      "Because I would promise her<br>a listening ear<br>when the world becomes too loud.",
      "Her personal back<br>when life decides to throw punches.",
      "An emotional cushion<br>for the days she forgets<br>she is allowed to be tired.",
      "A best friend<br>before I ever try to be her man.",
      "I would learn her.",
      "Not the way men learn a subject<br>just before an examination,<br>but the way a man learns scripture<br>when he is trying to find himself<br>inside the pages.",
      "I want to learn her<br>from cover to cover.",
      "<span class=\"divider\"><span>her books</span></span>",
      "<em>Her Genesis:</em><br>where she began.",
      "<em>Her Exodus:</em><br>what she survived.",
      "<em>Her Proverbs:</em><br>the wisdom she carries.",
      "<em>Her Psalms:</em><br>the things she only tells God.",
      "<em>Her Lamentations:</em><br>the wounds she doesn't advertise.",
      "And <em>her Revelations:</em><br>the parts of her<br>that only time<br>and trust<br>are allowed to uncover.",
      "<span class=\"divider\"><span>the book, opened</span></span>",
      "So when somebody asks me<br>why I love her,<br>I won't need a speech.<br>I'll simply open the book.",
      "Here is her laughter.",
      "Here is the scar<br>she stopped explaining.",
      "Here is the dream<br>she almost abandoned.",
      "Here is the insecurity<br>she hides behind confidence.",
      "Here is the little girl<br>inside the woman<br>who still wants somebody<br>to tell her,",
      "\"You don't always have to be strong.\"",
      "And here…<br>here is where I learned<br>how to love her properly.",
      "Because I don't just want<br>to be the man she loves.",
      "I want to become<br>the man her love<br>doesn't have to recover from.",
      "I want to know<br>when she needs an embrace<br>and when she needs space.",
      "When she wants advice<br>and when she only needs<br>somebody to sit beside her<br>while the storm finishes speaking.",
      "I want to know<br>the difference between<br>her \"I'm fine\"<br>and her I'm fine.",
      "There is a difference.",
      "And if anybody ever gives her<br>a reason to write Lamentations again,<br>God help me…<br>because I will remember<br>that Kings were written<br>long before I was born,<br>but I have no intention<br>of letting anybody write<br>the ending of her story for her.",
      "<span class=\"divider\"><span>§</span></span>",
      "I want to build with her.",
      "Not some fairytale castle<br>that collapses the moment<br>real life knocks.",
      "I mean something with foundations.",
      "Something that can survive<br>bad grades,<br>bad days,<br>empty pockets,<br>misunderstandings,<br>long silences,<br>and the ordinary wahala<br>that comes with being human.",
      "I want a love<br>that can sit in the kitchen<br>with us when romance has gone quiet.",
      "A love that can survive<br>when neither of us<br>looks poetic.",
      "A love that understands<br>that sometimes devotion<br>is not flowers.",
      "Sometimes it is patience.",
      "Sometimes it is listening.",
      "Sometimes it is staying gentle<br>when anger would be easier.",
      "Sometimes it is saying,<br>\"Come, let's fix this.\"",
      "And sometimes:<br>it is admitting,<br>\"I was wrong.\"",
      "Because I am not looking<br>for a woman to worship.",
      "I am looking for a woman<br>to walk beside.",
      "A woman with enough fire<br>to challenge me<br>and enough tenderness<br>to remind me<br>why I should never stop growing.",
      "And I am ready<br>to learn how to be hers.",
      "Not perfectly.<br>But deliberately.",
      "I will study the language<br>of her heart<br>until I stop needing subtitles.",
      "I will know her seasons.<br>Her winter.<br>Her rain.<br>Her Harmattan.<br>Her morning.<br>Her midnight.",
      "And when she asks me<br>how I know her so well,<br>I will tell her:",
      "\"I paid attention.\""
    ]
  },
  {
    id: "grandmas-kitchen",
    title: "Grandma's Kitchen",
    date: "2026",
    tags: ["family", "home", "ghana", "legacy"],
    cover: "grandmas-kitchen.PNG",
    lines: [
      "In the heart of Accra, where the sun kisses the rusted rooftops and the air hums with the rhythm of palm fronds, there lies a kitchen, a sanctuary of love and sustenance. It belongs to Grandma Akua, the matriarch of our family, her laughter etched into the wooden beams, her wisdom simmering in the bubbling pots.",
      "",
      "I. Sunrise Aromas",
      "",
      "At dawn, when the roosters stretch their wings and the sky blushes with saffron hues, Grandma's kitchen awakens. The door creaks open, revealing a world of fragrant secrets. The walls wear coats of ochre, stained by years of spices, turmeric, ginger, and the elusive grains of paradise. The air dances with the promise of breakfast: banku and okro soup, a symphony of flavors.",
      "",
      "II. The Cauldron's Song",
      "",
      "Grandma's cauldron, an ancient iron vessel, sits atop the charcoal stove. She stokes the flames, her hands weathered but nimble. Into the pot, she pours her love: chunks of tilapia, yam, and plantains. The water sings as it embraces the ingredients, and the aroma wraps around us like a warm embrace. We gather, hungry souls drawn by the magic of simmering memories.",
      "",
      "III. Palm Wine Whispers",
      "",
      "On special occasions, Grandma fetches a calabash of palm wine. Its amber hue reflects stories of ancestors who tapped the sap from towering palms. We sip, and the liquid sings of sun soaked afternoons and whispered dreams. Grandma's eyes crinkle as she recounts tales of resilience, of how the palm tree bends but never breaks.",
      "",
      "IV. Jollof Alchemy",
      "",
      "Ah, the legendary jollof rice! Grandma's version is an alchemical wonder. She sautés onions until they weep sweetness, then adds tomatoes, red as the setting sun. The rice joins the party, absorbing the crimson elixir. She sprinkles in her secret blend of spices, cayenne, cloves, and a pinch of nostalgia. The pot lid clinks shut, and we wait, mouths watering.",
      "",
      "V. Garden of Greens",
      "",
      "Grandma tends a garden behind the kitchen. There, okra stretches toward the sky, and cassava leaves rustle secrets. She plucks kontomire leaves, their emerald veins pulsing with life. In her mortar, she grinds shito, a fiery blend of chilies, dried fish, and shrimp. The result: a sauce that ignites tongues and warms hearts.",
      "",
      "VI. Fufu's Dance",
      "",
      "When the sun dips low, signaling dinner, Grandma's fufu dance begins. She pounds yam and plantains into submission, her pestle striking the wooden mortar in rhythmic beats. The fufu emerges, a cloud of starchy delight. We dip it into groundnut soup, our fingers sticky with tradition. The kitchen walls absorb our laughter, becoming witnesses to our communion.",
      "",
      "VII. Moonlit Blessings",
      "",
      "As the moon rises, Grandma stirs her waakye pot. Rice and beans meld into a mosaic of sustenance. She adds sorghum leaves, gari, and a dash of nostalgia. We sit under the mango tree, plates balanced on our laps. The night cradles us, and Grandma's kitchen becomes a haven of belonging. We taste the love she pours into every grain, every leaf, every memory.",
      "",
      "And so, in Grandma's kitchen, time folds like a well worn recipe. We savor the flavors of Ghana, the tang of tamarind, the warmth of sobolo, the laughter that seasons every dish. For Grandma Akua, cooking is not mere sustenance; it's a symphony of love, a legacy passed down through generations. And when we close our eyes, we can still taste the sunsets she stirred into her pots, the sunsets that linger on our tongues."
    ]
  },
  {
    id: "garden",
    title: "GARDEN",
    date: "2026",
    tags: ["love", "loss"],
    cover: "garden.PNG",
    lines: [
      "How do you manage to move me from frying pan to fire every time you cross my mind.",
      "You left my calm soul looking for a bottle to drown itself in.",
      "But do I bother?",
      "Even drunker than a priest after Sunday confession, I still can't find my peace in the brighter day.",
      "",
      "I stood by you through rain, through sun, through the in-between days that don't have a name.",
      "I fought off everything that came for you.",
      "I watered your garden every single night, learned which flowers needed less, which ones needed more, and forgot to ask the same of mine.",
      "",
      "My own ground went quiet.",
      "I didn't hear it dying. I was too busy learning how to arrange someone else's bouquet.",
      "",
      "Now I stand outside a fence that used to be mine and watch another man walk through it like he built it.",
      "His hands don't know what my hands know.",
      "He's never smelled that particular soil after rain.",
      "But he says it anyway, easy, like breathing:",
      "\"This is my garden now.\"",
      "",
      "And I laugh.",
      "Because laughing is cheaper than the alternative.",
      "They mock me for leaving my own ground untended, for giving years away to something that was never going to give them back.",
      "",
      "But what is love without the madness of that.",
      "What is a man without a few decisions he can't explain without laughing at himself.",
      "",
      "So here I am,",
      "standing at a fence that isn't mine ,",
      "trying to find the words to say sorry",
      "to the only thing that never asked nothing of me but attention."
    ]
  }
];
